/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selenium4.demo;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import java.util.HashMap;
import java.util.Map;
import static org.openqa.selenium.support.locators.RelativeLocator.with;


class AppTest {
    @Test
    void relativeSelector() throws InterruptedException {
        // 1. Configuration steps;
        String expectedTitle = "Flights from Paris to Dublin:";
        System.setProperty("webdriver.chrome.driver", "c:/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://blazedemo.com/");
        // 2. Retrieve the select "Destination city" and select option 'Dublin';
        WebElement toDestination = driver.findElement(By.cssSelector("[name='toPort']"));
        Select selectElement = new Select(toDestination);
        selectElement.selectByVisibleText("Dublin");
        // 3. Use Relative Locator 'below' to retrieve the "Find Flights" button;
        WebElement findFlightsButton = driver.findElement(with(By.tagName("input")).below(toDestination));
        findFlightsButton.click();
        // 4. Assert that the button was clicked by validating page title.
        String actualTitle = driver.findElement(By.tagName("h3")).getText();
        Assertions.assertEquals(expectedTitle, actualTitle);
        Thread.sleep(3000);
        driver.quit();
    }

    @Test
    void setGeolocation() throws InterruptedException {
        // 1. Configuration Steps
        String expectedAddress = "Calle 50 Poniente, 77510 Cancun, ROO, Mexico";
        System.setProperty("webdriver.chrome.driver", "c:/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        // 2. Create map with arguments for "Emulate.setGeolocationOverride"
        Map<String, Object> coordinatesMap = new HashMap<String, Object>();
        coordinatesMap.put("latitude", 25.761681);
        coordinatesMap.put("longitude", -80.191788);
        coordinatesMap.put("accuracy", 1);
        // 3. Calls CDP's "Emulation.setGeolocationOverride" to set new geolocation
        ((ChromeDriver)driver).executeCdpCommand("Emulation.setGeolocationOverride", coordinatesMap);
        driver.get("https://www.gps-coordinates.net/my-location");
        Thread.sleep(3000);
        // 4. Asserts that the Address shown is Cancún/Mexico
        String actualAddress = driver.findElement(By.id("addr")).getText();
        Assertions.assertEquals(expectedAddress, actualAddress);
        driver.quit();
    }
}
